# Theme settings
snet:
    baseurl: "https://dev.singularitynet.io"
    color_theme: blue
    google_analytics:
        tracking_code: UA-107763881-9
    comments:
        disqus_forum_shortname: singularitynet
#github:
#  repository_url: https://github.com/singnet/dev-portal
# SASS settings
sass:
    sass_dir: ./theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./theme/_layouts
includes_dir: ./theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md', 'template.md' ]
permalink: /:title/
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
  - feedjira
  - httparty
collections:
  - external_feed
